# Generated by Django 5.2.7 on 2025-10-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=100)),
                ('precios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entregas', models.CharField(max_length=100)),
                ('licencia_permisos', models.CharField(max_length=100)),
            ],
        ),
    ]
